# Generated by Django 6.0 on 2025-12-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='sessions/audio/')),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('record', 'Record')], default='upload', max_length=20)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('processing', 'Processing'), ('completed', 'Completed')], default='recorded', max_length=20)),
                ('session_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient')),
            ],
            options={
                'db_table': 'session',
                'ordering': ['-session_date'],
            },
        ),
    ]
