# Generated by Django 5.2.10 on 2026-01-14 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_email', ''), _negated=True), fields=('therapist', 'contact_email'), name='unique_patient_email_per_therapist'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_phone', ''), _negated=True), fields=('therapist', 'contact_phone'), name='unique_patient_phone_per_therapist'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('therapist', 'national_id'), name='unique_patient_national_id_per_therapist'),
        ),
    ]
