# Generated by Django 6.0 on 2025-12-18 17:10

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='audio_file',
            field=models.FileField(upload_to='sessions/audio/', validators=[patients.models.validate_audio_extension]),
        ),
    ]
