# Generated by Django 5.2.10 on 2026-01-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
    ]
