# Generated by Django 5.2.10 on 2026-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
