# Generated by Django 5.2.10 on 2026-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
