# Generated by Django 5.2.10 on 2026-01-14 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='uniq_patient_email_per_therapist',
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_email__isnull', False), models.Q(('contact_email', ''), _negated=True)), fields=('therapist', 'contact_email'), name='uniq_patient_email_per_therapist'),
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
