# Generated by Django 6.0 on 2025-12-22 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='last_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='last_error_stage',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='session_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('uploaded', 'Uploaded'), ('recorded', 'Recorded'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='empty', max_length=30),
        ),
        migrations.CreateModel(
            name='SessionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('original_filename', models.CharField(max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='therapy_sessions.therapysession')),
            ],
        ),
    ]
