# Generated by Django 6.0 on 2025-12-24 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_sessiontranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='sessions/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a'])]),
        ),
    ]
