# Generated by Django 6.0 on 2025-12-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_sessiontranscript'),
        ('therapy_sessions', '0002_therapysession_last_error_message_and_more'),
    ]

    operations = [
    ]
