# Generated by Django 6.0 on 2025-12-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0003_merge_20251224_1447'),
        ('therapy_sessions', '0003_sessionreport'),
    ]

    operations = [
    ]
