# Generated by Django 6.0 on 2025-12-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0004_merge_0003_merge_20251224_1447_0003_sessionreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionaudio',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='sessionaudio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
