# Generated by Django 5.2.9 on 2026-01-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0005_rename_uploaded_at_sessionaudio_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapysession',
            options={'ordering': ['-created_at']},
        ),
    ]
