# Generated by Django 4.2.27 on 2025-12-11 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('medical_history', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialty_tmp', models.CharField(blank=True, max_length=255)),
                ('license_number_tmp', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('is_licensed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Therapists',
            },
            bases=('users.user',),
        ),
    ]
