# Generated by Django - edited to ensure RemoveField happens before RenameField
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient_therapist'),
    ]

    operations = [
        # 1) Remove the fields from the base User table first (so no clash)
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),

        # 2) Now rename the temporary fields in Therapist to final names
        migrations.RenameField(
            model_name='therapist',
            old_name='specialty_tmp',
            new_name='specialty',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='license_number_tmp',
            new_name='license_number',
        ),

    ]