# Generated by Django 6.0 on 2025-12-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_therapistprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=True),
        ),
    ]
