# Generated by Django 6.0 on 2025-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
